export const crownOfInnerQuiteTasks = [
  'Take three slow breaths before opening another app.',
  'Pause for 10 seconds before speaking once today.',
  'Notice your posture right now. Adjust gently.',
  'Drink a glass of water without distraction.',
  'Spend one minute looking at the sky or ceiling.',
  'Walk slower for a few steps today.',
  'Let one thought pass without following it.',
  'Sit quietly for 60 seconds. Do nothing else.',
  'Lower your shoulders once today.',
  'Listen fully when someone speaks.',
  'Breathe out longer than you breathe in.',
  'Touch something solid and feel its weight.',
  'Delay one reaction by a moment.',
  'Close your eyes for three breaths.',
  'Notice a sound you usually ignore.',
  'Relax your jaw when you remember.',
  'Stand still for 30 seconds.',
  'Take a slow breath before checking messages.',
  'Feel your feet on the ground.',
  'Choose silence instead of explanation once.',
  'Let today be simple.',
  'Notice when you rush — and soften.',
  'Sit comfortably and do nothing for one minute.',
  'Observe your breath without changing it.',
  'Rest your eyes for a few seconds.',
  'Finish one action without multitasking.',
  'Allow a pause between thoughts.',
  'Move with intention for one small action.',
  'Accept the current moment as it is.',
  'End the day without rushing the next one.',
];
