export const crownOfInnerQuietQuotes = [
  'Silence is not empty. It is listening.',
  'You don’t need to hurry what is already yours.',
  'Calm is a form of strength.',
  'The quiet path is still a path.',
  'Nothing important needs to shout.',
  'Stillness reveals what noise hides.',
  'You are allowed to slow down.',
  'Presence is enough for today.',
  'Peace begins when effort ends.',
  'The night knows how to wait.',
  'What matters stays, even in silence.',
  'Awareness is gentle, not forceful.',
  'You are not late.',
  'Quiet moments shape strong minds.',
  'There is clarity in pause.',
  'The body understands before words appear.',
  'Not everything needs a response.',
  'Depth grows in still water.',
  'Silence is a companion, not a void.',
  'You don’t need to prove calm.',
  'Rest is part of the path.',
  'Let the moment arrive on its own.',
  'Strength does not rush.',
  'The quiet choice is often the right one.',
  'Nothing is missing right now.',
  'Awareness begins with stopping.',
  'Listen before moving forward.',
  'Calm attention changes everything.',
  'Be here. That is enough.',
  'Silence holds more than answers.',
];
